language: csharp
mono: none
dotnet: 1.0.4
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required      
    - os: osx # OSX 10.11
      osx_image: xcode7.3      
    - os: osx # OSX 10.12
      osx_image: xcode8.1      

# branches to build 
branches:
  only:
    - master

script:
  - chmod +x build.sh
  - ./build.sh